language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

jdk:
  - oraclejdk8

env:
  global:
  - secure: "2TamMgeH+NcX2yJkLWYvJLD1BMiUCoyFn9fOmY+WyVoz8uVEOba0zeIncj2MYkJ3bF67oMxc13d1mkr4tV3nLTm/vTHQDUtzFFadX3Beuxc678vXf5GN7Y9b5TE9xjr2VIBsNdeWNWVeyKCHCH92LSuv9+T/GK67Qgf3xroOWFT37wOOIsWsgtGeCtE33eeMEa11ZzxXyGRjr+r9Kq/Qbjb6ERb6hDYqXxQJDSxIU8z8gXp34zOCKujPOMeBybYDq0B3DLKLh4/Nm3h3YSTNzsrzBCqsI5BbKzAI9DedV+X1J6v/U3RCajQrvXKNiSFSBKvyfmf2E4r78auA4scMkUtKr40MUltSKkiQsCs8dzzQ3POIQgYP9asKAl/DBFnPMyTstoCBqLSQde42VZ17urZwYpVXuRAR7TXgEbHQTKvvck5ZebrmYt1CGngY4ALGOaiEhjlLf05LF8ARa5WlRJ9DhUM/8DEpWIp++obBubbSTRHWxjP/X4ZKb9QtUKSWIlCE5lhMLWcELjqocjxjuEjNUdCTz1Ha9axFf5ClgQ1CP/C+zLeRXceK+CTSd8HQZ7jsdu21Ca3lu89LjRvQeiNj48A9bAR2XBBYOu1S75x44CKr9ndVCxlLZXzrQPQDFZ9J1NZZ2DROiDZ7GXLK21xcBpNUf9su9XNRae76ucc="
  - secure: "oXfHkp/v43fHOc/bEPnVxfV9bLgHWOl3Sb508zWovV3t42wJdPQDZTquA3vNT2NrC0pdcAqDLtlACrdqyddB/lXnbyjhxTT5RnuvdmtiylzWskzfa1D3Cj2hCNkH5N8Bd37fgwklb22TM4ZSA8Ixk0ppFJN5DoNyKWYk+Cs26yOJAs0KGs2dDSIBV7P004s+541aI1B6O03TTgJD85p3kiPr74crl4nrrQJYHogBMx13INZgCHGbKHcgay3xbx/QXHYi6maN/RRPUx4xLh6MA6bPgVPD2EJ6CPH6k38LhyOdw27fqqPgNAUnVawRmLVPGnuH/Dmu8fply5m1ZAx2dDwrKnXmfEoHFEk142+mJVkoc5iFtHeib2T4I3WUAqpn4JUeIqCq3RmLBq5mK07yHWw4shr/7WMCjgKlGd0WOa3aNQ4E7Zp0WdwEUgtcbln7S/VYS6kj/PKi+xA6+QqZnRHuZWNs2h7Iaj00f4QlyVlT5BBbq32+NbWBN3SvtibLKKEnjifttuzg6bys9s6x2SCoq7IteEZr+Zfhn2K58Foq3yeNBHhxLbdEEZcfYWEzPuVcx2KEOd0sscq0Y1k9EcZ4HFKQZv5EDKMGM9fZBn404TBaLcfJKE/v6oT4WAi66Wd3q+Gr3RxHw6TRXMIuIBWMaoOrqenWBfvqAnudAtU="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
